[tool.poetry]
name = "hospo-matcher"
version = "0.1.0"
description = ""
authors = ["Callum Macaskill"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
pre-commit = "^3.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
